//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgCheckWork {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class CheckSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static CheckSet defaultInstance = ((CheckSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CheckSet())));
        
        public static CheckSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string Check_Work {
            get {
                return ((string)(this["Check_Work"]));
            }
            set {
                this["Check_Work"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string Check_UnWork {
            get {
                return ((string)(this["Check_UnWork"]));
            }
            set {
                this["Check_UnWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Check_ {
            get {
                return ((string)(this["Check_"]));
            }
            set {
                this["Check_"] = value;
            }
        }
    }
}
